/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as BudgetWorksheetRouteImport } from './routes/budget-worksheet'
import { Route as BudgetsRouteImport } from './routes/budgets'
import { Route as CategoryBudgetsRouteImport } from './routes/category-budgets'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RecordIncomeRouteImport } from './routes/record-income'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SavingsGoalsRouteImport } from './routes/savings-goals'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TrackExpensesRouteImport } from './routes/track-expenses'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as ResetPasswordTokenRouteImport } from './routes/reset-password.$token'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetWorksheetRoute = BudgetWorksheetRouteImport.update({
  id: '/budget-worksheet',
  path: '/budget-worksheet',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetsRoute = BudgetsRouteImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryBudgetsRoute = CategoryBudgetsRouteImport.update({
  id: '/category-budgets',
  path: '/category-budgets',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordIncomeRoute = RecordIncomeRouteImport.update({
  id: '/record-income',
  path: '/record-income',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SavingsGoalsRoute = SavingsGoalsRouteImport.update({
  id: '/savings-goals',
  path: '/savings-goals',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackExpensesRoute = TrackExpensesRouteImport.update({
  id: '/track-expenses',
  path: '/track-expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordTokenRoute = ResetPasswordTokenRouteImport.update({
  id: '/$token',
  path: '/$token',
  getParentRoute: () => ResetPasswordRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/budget-worksheet': typeof BudgetWorksheetRoute
  '/budgets': typeof BudgetsRoute
  '/category-budgets': typeof CategoryBudgetsRoute
  '/dashboard': typeof DashboardRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/goals': typeof GoalsRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/record-income': typeof RecordIncomeRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRouteWithChildren
  '/savings-goals': typeof SavingsGoalsRoute
  '/settings': typeof SettingsRoute
  '/track-expenses': typeof TrackExpensesRoute
  '/transactions': typeof TransactionsRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/budget-worksheet': typeof BudgetWorksheetRoute
  '/budgets': typeof BudgetsRoute
  '/category-budgets': typeof CategoryBudgetsRoute
  '/dashboard': typeof DashboardRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/goals': typeof GoalsRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/record-income': typeof RecordIncomeRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRouteWithChildren
  '/savings-goals': typeof SavingsGoalsRoute
  '/settings': typeof SettingsRoute
  '/track-expenses': typeof TrackExpensesRoute
  '/transactions': typeof TransactionsRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/budget-worksheet': typeof BudgetWorksheetRoute
  '/budgets': typeof BudgetsRoute
  '/category-budgets': typeof CategoryBudgetsRoute
  '/dashboard': typeof DashboardRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/goals': typeof GoalsRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/record-income': typeof RecordIncomeRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRouteWithChildren
  '/savings-goals': typeof SavingsGoalsRoute
  '/settings': typeof SettingsRoute
  '/track-expenses': typeof TrackExpensesRoute
  '/transactions': typeof TransactionsRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/budget-worksheet'
    | '/budgets'
    | '/category-budgets'
    | '/dashboard'
    | '/features'
    | '/forgot-password'
    | '/goals'
    | '/insights'
    | '/login'
    | '/record-income'
    | '/reports'
    | '/reset-password'
    | '/savings-goals'
    | '/settings'
    | '/track-expenses'
    | '/transactions'
    | '/reset-password/$token'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/budget-worksheet'
    | '/budgets'
    | '/category-budgets'
    | '/dashboard'
    | '/features'
    | '/forgot-password'
    | '/goals'
    | '/insights'
    | '/login'
    | '/record-income'
    | '/reports'
    | '/reset-password'
    | '/savings-goals'
    | '/settings'
    | '/track-expenses'
    | '/transactions'
    | '/reset-password/$token'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/budget-worksheet'
    | '/budgets'
    | '/category-budgets'
    | '/dashboard'
    | '/features'
    | '/forgot-password'
    | '/goals'
    | '/insights'
    | '/login'
    | '/record-income'
    | '/reports'
    | '/reset-password'
    | '/savings-goals'
    | '/settings'
    | '/track-expenses'
    | '/transactions'
    | '/reset-password/$token'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  BudgetWorksheetRoute: typeof BudgetWorksheetRoute
  BudgetsRoute: typeof BudgetsRoute
  CategoryBudgetsRoute: typeof CategoryBudgetsRoute
  DashboardRoute: typeof DashboardRoute
  FeaturesRoute: typeof FeaturesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GoalsRoute: typeof GoalsRoute
  InsightsRoute: typeof InsightsRoute
  LoginRoute: typeof LoginRoute
  RecordIncomeRoute: typeof RecordIncomeRoute
  ReportsRoute: typeof ReportsRoute
  ResetPasswordRoute: typeof ResetPasswordRouteWithChildren
  SavingsGoalsRoute: typeof SavingsGoalsRoute
  SettingsRoute: typeof SettingsRoute
  TrackExpensesRoute: typeof TrackExpensesRoute
  TransactionsRoute: typeof TransactionsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budget-worksheet': {
      id: '/budget-worksheet'
      path: '/budget-worksheet'
      fullPath: '/budget-worksheet'
      preLoaderRoute: typeof BudgetWorksheetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budgets': {
      id: '/budgets'
      path: '/budgets'
      fullPath: '/budgets'
      preLoaderRoute: typeof BudgetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category-budgets': {
      id: '/category-budgets'
      path: '/category-budgets'
      fullPath: '/category-budgets'
      preLoaderRoute: typeof CategoryBudgetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/record-income': {
      id: '/record-income'
      path: '/record-income'
      fullPath: '/record-income'
      preLoaderRoute: typeof RecordIncomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/savings-goals': {
      id: '/savings-goals'
      path: '/savings-goals'
      fullPath: '/savings-goals'
      preLoaderRoute: typeof SavingsGoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track-expenses': {
      id: '/track-expenses'
      path: '/track-expenses'
      fullPath: '/track-expenses'
      preLoaderRoute: typeof TrackExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password/$token': {
      id: '/reset-password/$token'
      path: '/$token'
      fullPath: '/reset-password/$token'
      preLoaderRoute: typeof ResetPasswordTokenRouteImport
      parentRoute: typeof ResetPasswordRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ResetPasswordRouteChildren {
  ResetPasswordTokenRoute: typeof ResetPasswordTokenRoute
}

const ResetPasswordRouteChildren: ResetPasswordRouteChildren = {
  ResetPasswordTokenRoute: ResetPasswordTokenRoute,
}

const ResetPasswordRouteWithChildren = ResetPasswordRoute._addFileChildren(
  ResetPasswordRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  BudgetWorksheetRoute: BudgetWorksheetRoute,
  BudgetsRoute: BudgetsRoute,
  CategoryBudgetsRoute: CategoryBudgetsRoute,
  DashboardRoute: DashboardRoute,
  FeaturesRoute: FeaturesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GoalsRoute: GoalsRoute,
  InsightsRoute: InsightsRoute,
  LoginRoute: LoginRoute,
  RecordIncomeRoute: RecordIncomeRoute,
  ReportsRoute: ReportsRoute,
  ResetPasswordRoute: ResetPasswordRouteWithChildren,
  SavingsGoalsRoute: SavingsGoalsRoute,
  SettingsRoute: SettingsRoute,
  TrackExpensesRoute: TrackExpensesRoute,
  TransactionsRoute: TransactionsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
